<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CurrentCar;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * CurrentCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrentCarRepository extends \Doctrine\ORM\EntityRepository
{

    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $metadata = null)
    {
        parent::__construct($em, $metadata == null ?
            new Mapping\ClassMetadata(CurrentCar::class) :
            $metadata);
    }

    public function save(CurrentCar $currentCar)
    {
        try {
            $this->_em->persist($currentCar);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    public function delete(CurrentCar $currentCar)
    {
        try {
            $this->_em->remove($currentCar);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    public function edit(CurrentCar $currentCar)
    {
        try {
            $this->_em->merge($currentCar);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
