<?php

namespace AppBundle\Repository;

use AppBundle\Entity\PreviousCar;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * PreviousCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreviousCarRepository extends \Doctrine\ORM\EntityRepository
{

    public function __construct(EntityManagerInterface $em, Mapping\ClassMetadata $metadata = null)
    {
        parent::__construct($em, $metadata == null ?
            new Mapping\ClassMetadata(PreviousCar::class) :
            $metadata);
    }

    public function save(PreviousCar $previousCar)
    {
        try {
            $this->_em->persist($previousCar);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    public function delete(PreviousCar $previousCar)
    {
        try {
            $this->_em->remove($previousCar);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    public function edit(PreviousCar $previousCar)
    {
        try {
            $this->_em->merge($previousCar);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
